# Generated by Django 4.2.19 on 2025-05-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('soon', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('genre', models.CharField(max_length=100)),
                ('tags', models.JSONField()),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('cycle_book', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(max_length=50)),
                ('year_of_publishing', models.PositiveIntegerField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('age_restriction', models.CharField(max_length=3)),
                ('cover_type', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('rating_value', models.FloatField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('image_link', models.URLField()),
            ],
        ),
    ]
