# Generated by Django 4.2.19 on 2025-06-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_authors_delete_author_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
