# Generated by Django 4.2.19 on 2025-06-20 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_bookrecommendation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrecommendation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookrecommendation',
            name='recommended_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookrecommendation',
            name='similarity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bookrecommendation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='books.book'),
        ),
        migrations.AlterUniqueTogether(
            name='bookrecommendation',
            unique_together={('book', 'recommended_book')},
        ),
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='score',
        ),
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='user',
        ),
        migrations.CreateModel(
            name='UserBookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
