# Generated by Django 4.2.19 on 2025-06-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookrecommendation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indices', models.JSONField(blank=True, default=list)),
                ('values', models.JSONField(blank=True, default=list)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='books.book')),
            ],
        ),
    ]
