# Generated by Django 4.2.19 on 2025-06-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_reviewsentiment_reviewembedding_booktopicvector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktopicvector',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reviewembedding',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewsentiment',
            name='review',
        ),
        migrations.AddField(
            model_name='bookview',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='BookEmbedding',
        ),
        migrations.DeleteModel(
            name='BookTopicVector',
        ),
        migrations.DeleteModel(
            name='ReviewEmbedding',
        ),
        migrations.DeleteModel(
            name='ReviewSentiment',
        ),
    ]
