# Generated by Django 4.2.19 on 2025-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_booktopicvector_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookview',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookview',
            name='scroll_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bookview',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
