# Generated by Django 4.2.19 on 2025-06-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_reviewsentiment_reviewembedding_booktopicvector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvector',
            name='w2v_vector',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
