# Generated by Django 4.2.19 on 2025-06-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_bookvector_w2v_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
