# Generated by Django 4.2.19 on 2025-07-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_usersearchquery_remove_booktopicvector_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(blank=True, default=list)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='books.review')),
            ],
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('vector', models.JSONField()),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='BookEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(blank=True, default=list)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='books.book')),
            ],
        ),
    ]
