# Generated by Django 4.2.19 on 2025-07-07 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0018_reviewembedding_embedding_bookembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopicVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_vector', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
