# Generated by Django 4.2.19 on 2025-07-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_usertopicvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='books.review')),
            ],
        ),
        migrations.CreateModel(
            name='BookTopicVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indices', models.JSONField(blank=True, default=list)),
                ('values', models.JSONField(blank=True, default=list)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_vector', to='books.book')),
            ],
        ),
    ]
