# Generated by Django 4.2.19 on 2025-07-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_reviewsentiment_booktopicvector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsentiment',
            name='review',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='favorite_authors',
            field=models.ManyToManyField(related_name='profile_users', through='books.FavoriteAuthors', to='books.author'),
        ),
        migrations.DeleteModel(
            name='BookTopicVector',
        ),
        migrations.DeleteModel(
            name='ReviewSentiment',
        ),
    ]
