# Generated by Django 4.2.19 on 2025-07-14 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0021_remove_reviewsentiment_review_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'author'), ('user', 'cycle')},
        ),
    ]
